apiVersion: v2
name: predixy
description: Helm chart for Predixy Redis Cluster proxy
type: application
version: 0.1.2
appVersion: "20240424"
keywords:
  - redis
  - redis-cluster
  - predixy
  - proxy
sources:
  - https://github.com/joyieldInc/predixy
