apiVersion: v1
kind: Secret
metadata:
  name: {{ include "predixy.fullname" . }}-config
  labels:
    {{- include "predixy.labels" . | nindent 4 }}
type: Opaque
stringData:
  predixy.conf: |
{{- if .Values.customConfig }}
{{ .Values.customConfig | indent 4 }}
{{- else }}
    Name {{ .Values.predixy.name }}
    Bind {{ .Values.predixy.bind }}
    WorkerThreads {{ .Values.predixy.workerThreads }}
    ClientTimeout {{ .Values.predixy.clientTimeout }}

    LogVerbSample {{ .Values.predixy.logSamples.verb }}
    LogDebugSample {{ .Values.predixy.logSamples.debug }}
    LogInfoSample {{ .Values.predixy.logSamples.info }}
    LogNoticeSample {{ .Values.predixy.logSamples.notice }}
    LogWarnSample {{ .Values.predixy.logSamples.warn }}
    LogErrorSample {{ .Values.predixy.logSamples.error }}

{{- if .Values.predixy.clientAuth.enabled }}
    Authority {
        Auth "{{ .Values.predixy.clientAuth.password }}" {
            Mode {{ .Values.predixy.clientAuth.mode }}
        }
    }
{{- end }}

    ClusterServerPool {
        Password "{{ .Values.predixy.cluster.password }}"
        MasterReadPriority {{ .Values.predixy.cluster.masterReadPriority }}
        StaticSlaveReadPriority {{ .Values.predixy.cluster.staticSlaveReadPriority }}
        DynamicSlaveReadPriority {{ .Values.predixy.cluster.dynamicSlaveReadPriority }}
        RefreshInterval {{ .Values.predixy.cluster.refreshInterval }}
        ServerTimeout {{ .Values.predixy.cluster.serverTimeout }}
        ServerFailureLimit {{ .Values.predixy.cluster.serverFailureLimit }}
        ServerRetryTimeout {{ .Values.predixy.cluster.serverRetryTimeout }}
        KeepAlive {{ .Values.predixy.cluster.keepAlive }}
        Servers {
{{- range .Values.predixy.cluster.servers }}
            + {{ . }}
{{- end }}
        }
    }
{{- end }}